FROM golang:1.15.1-alpine3.12 AS builder
ADD . /overseer/
WORKDIR /overseer
RUN mkdir build
RUN go mod download
RUN go build -o build ./...

FROM alpine:latest
WORKDIR /root/
COPY --from=builder /overseer/build/aggregator .
CMD ["./aggregator"]
