FROM golang:1.15.1-alpine3.12 AS builder
WORKDIR /overseer
RUN mkdir build
COPY go.mod go.sum ./
RUN go mod download
COPY . .
RUN go build -o build ./...

FROM alpine:latest
WORKDIR /root/
RUN mkdir frontend/
COPY --from=builder /overseer/build/presenter .
COPY --from=builder /overseer/frontend frontend/
CMD ["./presenter"]
