version: "3.4"

services:
    agent:
        build:
            context: .
            dockerfile: Dockerfile.agent
        container_name: agent
        restart: always
        depends_on:
            - rabbitmq
        environment:
            # URLS: "webserver-1,webserver-2"  # specify here target servers to monitor
            QUEUE_ADDR: "amqp://guest:guest@rabbitmq"

    aggregator:
        build:
            context: .
            dockerfile: Dockerfile.aggregator
        container_name: aggregator
        restart: always
        depends_on:
            - rabbitmq
        environment:
            QUEUE_ADDR: "amqp://guest:guest@rabbitmq"

    presenter:
        build:
            context: .
            dockerfile: Dockerfile.presenter
        container_name: presenter
        restart: always
        depends_on:
            - rabbitmq
        environment:
            QUEUE_ADDR: "amqp://guest:guest@rabbitmq"
        ports:
            - "17657:17657"

    rabbitmq:
        image: rabbitmq
        container_name: rabbitmq
        expose:
            - 5672
