FROM golang:1.15.1-alpine3.12 AS builder
ADD . /overseer/
WORKDIR /overseer
RUN mkdir build
RUN go mod download
RUN go build -o build ./...

FROM alpine:latest
WORKDIR /root/
RUN mkdir frontend/
COPY --from=builder /overseer/build/presenter .
COPY --from=builder /overseer/frontend frontend/
CMD ["./presenter"]
